### ISSUE TITLE
講話的地方改成對話框

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/PWA-English-Speaking-Practice#10]

**Comment by pulipulichen** [comment]
https://codepen.io/martynchamberlin/pen/WdrBeZ

````html
<div class="trigger">
  <p>Hello world</p>
  
  <div class="popup">
    <div class="inner">I am a popup</div>
  </div>
</div>
````
````css
body {
  font-family: Helvetica;
  background: #ddd;
}

.trigger {
  margin: 150px auto 20px;
  width: 150px;
  position: relative;
  text-align: center;
}

.popup {
  position: absolute;
  left: 0;
  top: 80px;
  transform: translate3d(0, -50%, 0);
  box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.5);
  background: none;
  border-radius: 100px;
  width: 100%;
}

.popup:after {
  content: "";
  width: 20px;
  height: 20px;
  transform: rotate(-45deg);
  background: #fff;
  position: absolute;
  box-shadow: 1px 4px 8px rgba(0, 0, 0, 0.5);
  z-index: -1;
  top: -10px;
  left: calc(50% - 10px);
}

.inner {
  padding: 30px 0;
  background: #fff;
  border-radius: 100px;
}

````
